### ISSUE TITLE
How it is possible to run multiple sqls separated by semicolons with *sql.DB ?

### ISSUE THREAD

**Issue by sunfmin** [nsf/sqlbatch#1]
I run into this error with the latest PostgreSQL.

```
    utils_test.go:36: db exec error: pq: syntax error at or near "ASC" for query
        		DROP TABLE IF EXISTS "foo_bar";
        		CREATE TABLE foo_bar (
        			id INT NOT NULL,
        			foo STRING NOT NULL,
        			bar STRING NOT NULL,
        			created_at TIMESTAMP NOT NULL,
        			CONSTRAINT "primary" PRIMARY KEY (id ASC)
        		)
```

**Comment by LeKovr** [comment]
> I run into this error with the latest PostgreSQL.

This code throws an error in any postgresql version because `CONSTRAINT` term has the following [syntax](https://www.postgresql.org/docs/current/sql-createtable.html): `PRIMARY KEY ( column_name [, ... ] )`.

Meanwhile, "multiple sqls separated by semicolons" is supported well by postgresql at libpq level
